# Generated by Django 6.0.2 on 2026-03-02 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ward', models.CharField(max_length=100)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('assigned_doctor_id', models.IntegerField(blank=True, null=True)),
                ('created_by_staff_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_stage', models.IntegerField(choices=[(1, 'GOLD 1 - Mild'), (2, 'GOLD 2 - Moderate'), (3, 'GOLD 3 - Severe'), (4, 'GOLD 4 - Very Severe')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_classifications', to='patients.patient')),
            ],
            options={
                'db_table': 'gold_classification',
            },
        ),
        migrations.CreateModel(
            name='GasExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_hypoxemia', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('on_oxygen_therapy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_exchange_history', to='patients.patient')),
            ],
            options={
                'db_table': 'gas_exchange_history',
            },
        ),
        migrations.CreateModel(
            name='CurrentSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmrc_grade', models.IntegerField(choices=[(0, 'Grade 0'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')])),
                ('cough', models.BooleanField(default=False)),
                ('sputum', models.BooleanField(default=False)),
                ('wheezing', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('chest_tightness', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='patients.patient')),
            ],
            options={
                'db_table': 'current_symptoms',
            },
        ),
        migrations.CreateModel(
            name='BaselineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_previous_diagnosis', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='patients.patient')),
            ],
            options={
                'db_table': 'baseline_details',
            },
        ),
        migrations.CreateModel(
            name='ABGEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField(help_text='pH (7.35–7.45 normal)')),
                ('pao2', models.FloatField(help_text='PaO2 in mmHg')),
                ('paco2', models.FloatField(help_text='PaCO2 in mmHg')),
                ('hco3', models.FloatField(help_text='HCO3 in mEq/L')),
                ('fio2', models.FloatField(help_text='FiO2 fraction (0.21–1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abg_entries', to='patients.patient')),
            ],
            options={
                'db_table': 'abg_entry',
            },
        ),
        migrations.CreateModel(
            name='ReassessmentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2_checked', models.BooleanField(default=False)),
                ('resp_rate_checked', models.BooleanField(default=False)),
                ('consciousness_checked', models.BooleanField(default=False)),
                ('device_fit_checked', models.BooleanField(default=False)),
                ('abg_checked', models.BooleanField(default=False)),
                ('all_clear', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessments', to='patients.patient')),
            ],
            options={
                'db_table': 'reassessment_checklist',
            },
        ),
        migrations.CreateModel(
            name='SpirometryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fev1', models.FloatField(help_text='FEV1 in litres')),
                ('fev1_fvc', models.FloatField(help_text='FEV1/FVC ratio (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirometry_data', to='patients.patient')),
            ],
            options={
                'db_table': 'spirometry_data',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2', models.FloatField(help_text='SpO2 (%)')),
                ('resp_rate', models.IntegerField(help_text='Respiratory rate (breaths/min)')),
                ('heart_rate', models.IntegerField(help_text='Heart rate (bpm)')),
                ('temperature', models.FloatField(help_text='Temperature (°C)')),
                ('bp', models.CharField(help_text='Blood pressure e.g. 120/80', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
    ]
